version: "3.8"

services:
  nodejs-api:
    image: examen
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_examen
    depends_on:
      - mysql-service
    volumes:
      - .:/usr/src/app
    ports:
      - "3020:3019"
    networks:
      - service_examen_gestion_examen_default
    environment:
      DB_HOST: mysql-service
      DB_USER: root
      DB_PASSWORD: mysqlserver
      DB_PORT: 3306
      DB_DATABASE: examen
      APP_PORT: 3019

  mysql-service:
    image: mysql
    container_name: mysql-service-container-examen
    restart: always
    environment:
      MYSQL_DATABASE: examen
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: mysqlserver
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - service_examen_gestion_examen_default
    volumes:
      - service_examen_gestion_examen_default:/data/db
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  service_examen_gestion_examen_default:
    driver: bridge

volumes:
  service_examen_gestion_examen_default:
