apiVersion: v1
kind: Service
metadata:
  name: examen-service
  namespace: examen
spec:
  selector:
    app: examen
  ports:
    - protocol: TCP
      port: 3018
      targetPort: 3018
  type: LoadBalancer
