apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: examen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: amalseghaier/exam-kubernetes:latest    
          ports:
            - containerPort: 3990

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: examen
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3990
      targetPort: 3990
  type: LoadBalancer