apiVersion: apps/v1
kind: Deployment
metadata:
  name: examen-deployment
  namespace: examen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examen
  template:
    metadata:
      labels:
        app: examen
    spec:
      containers:
        - name: examen
          image: amalseghaier/examen_kubernetes:latest
          ports:
            - containerPort: 3019
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "mysqlserver"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "examen"
